function Rout = rpyRotMatrix(psi,theta,phi)
% Returns the rotation matrix after a series of rotations
% 1: yaw   of phi   degrees about the current z axis
% 2: pitch of theta degrees about the current y axis
% 3: roll  of psi   degrees about the current x axis
% all angles in radians
Rz = [cos(phi) -sin(phi) 0;...
    sin(phi) cos(phi) 0;...
    0 0 1];
Ry = [cos(theta) 0 sin(theta);...
    0 1 0;...
    -sin(theta) 0 cos(theta)];
Rx = [1 0 0;...
    0 cos(psi) -sin(psi);...
    0 sin(psi) cos(psi)];
Rout = Rz*Ry*Rx;
end